[project]
name = "window-actuator"
version = "0.1.0"
description = "Window driver to automate room ventilation with Home Assistant control"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "esptool",
    "micropython-esp8266-stubs",
    "rshell",
]

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = ["ext_modules"]
extend-exclude = ["firmware/manifest.py"]

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP", "B"]
ignore = []

[tool.ruff.lint.isort]
combine-as-imports = true
